### ISSUE TITLE
Updates for v1.1 / ANSI/NISO Z39.99-2017

### ISSUE THREAD

**Issue by zimeon** [resync/resync#24]
Update published 2017-02: http://www.openarchives.org/rs/1.1/resourcesync

**Comment by zimeon** [comment]
And see highlighted version: http://www.openarchives.org/rs/1.1/resourcesync_highlighted

**Comment by zimeon** [comment]
Change required is to add the `datetime` property and to separate use from that of `lastmod`. Though for filesystem operation we might want a flag that ties the two in lockstep.

**Comment by zimeon** [comment]
@markmatney - do you have any thoughts on how making changes for v1.1 would affect your use of this code? The addition of `datetime` to `Resource` would be an addition only so presumably harmless, bit changing to use that and `lastmod` in other code might have more impact?

**Comment by markmatney** [comment]
From [section 1.3](https://www.openarchives.org/rs/1.1/resourcesync_highlighted#Walkthrough) of the spec:
> The example also shows the use of the <lastmod> element to convey the modification times of the resources, and the datetime attribute of <rs:md> to convey the change time. In the case of the created resource, the datetime conveyed by the <lastmod> element is earlier than that of the datetime attribute, perhaps because the repository made an old file visible only at the datetime given.

I am using the [py-resourcesync](https://github.com/resourcesync/py-resourcesync) software (which includes `resync` as a dependency) for which I've developed an [OAI-PMH add-on](https://github.com/resourcesync/py-resourcesync/blob/master/resourcesync/generators/oaipmh_generator.py). That quote from section 1.3 notes the possibility of a distinction between "modification time" and "change time", where the latter may be the time when a repository made a resource public some time after it had been created ("publishing time"?). In OAI-PMH I don't believe there is any such distinction -- the only timestamp available is in the `header.datestamp` field, which for the purposes of `OAIPMHGenerator` I think can go in both a `Resource`'s `lastmod` and `datetime`.

As for changes to other parts of py-resourcesync besides `OAIPMHGenerator`, I'm not sure off the top of my head. @hariharshankar knows the code better than I do

**Comment by giorgiobasile** [comment]
FYI, the [rspub-core](https://github.com/EHRI/rspub-core) project, which is the precursor of py-resourcesync, had a [forked version of resync](https://github.com/EHRI/resync/tree/ehribranch) as a dependency in its requirements.txt. It supports some of the new 1.1 updates, including the `md_datetime` field, and I was using it in the [Elasticsearch extension](https://github.com/openminted/omtd-rspub-elastic) developed by CORE for the OpenMinTeD project, which has been than merged in py-resourcesync as a pluggable generator.
