### ISSUE TITLE
allow "resync" command line utility to accept a resourcelist named something other than "resourcelist.xml"

### ISSUE THREAD

**Issue by markmatney** [resync/resync#28]
I have a ResourceSync-enabled server with a valid resourcelist at `http://example.com/resourcesync/test/my-resourcelist.xml`. When I use the `resync` executable to do `resync -b http://example.com/resourcesync/test`, I get

```bash
FatalError: Can't read source resource list from http://example.com/resourcesync/test/resourcelist.xml (Failed to load sitemap/sitemapindex from http://example.com/resourcesync/test/resourcelist.xml (HTTP Error 404: Not Found))
```

because `resync` expects the file to be named a certain way (as `resourcelist.xml`), even though the [spec](https://www.openarchives.org/rs/1.1/resourcesync) places no such restriction on file names.

The `resync-explorer` executable, however, is able to discover resourcelists that are named something other than `resourcelist.xml`. Thus, it appears this functionality is implemented by the library, but it would be nice if `resync` was more flexible with the names of sitemaps it expects/accepts.

**Comment by zimeon** [comment]
Have you tried the (perhaps badly named) `--sitemap` flag? You can do something like:

```
> resync -v -b --sitemap http://example.com/xyz.xml http://example.com/ /tmp/example.com
Reading sitemap http://example.com/xyz.xml

FatalError: Can't read source resource list from http://example.com/xyz.xml (Failed to load sitemap/sitemapindex from http://example.com/xyz.xml (('http error', 404, 'Not Found', <httplib.HTTPMessage instance at 0x10d5c8ab8>)))
```

**Comment by markmatney** [comment]
Ah, I think I discovered that at one point, whoops. Thanks for the tip.
