### ISSUE TITLE
resource fetching mechanism, and lack of retry and timeout options, is inadequate in at least one case

### ISSUE THREAD

**Issue by markmatney** [resync/resync#34]
`resync` is [currently using `urllib.request.urlretrieve`](https://github.com/resync/resync/blob/041aead70e1209476202d359be46ccb734b9f312/resync/client.py#L501) to handle the data transfer of resources from remote server to local filesystem. I've observed a couple problems with this:

1) On some network errors, `urlretrieve` hangs indefinitely; for example, if, during a call to `urlretrieve`, a connection is established but the server doesn't send any data.
2) If an `IOError` is raised, `resync` either moves on to the next resource to download, or it exits completely, but won't retry the request. In some cases, a retry after a delay would have been successful.
3) `urlretrieve` has been designated as part of a legacy interface in the [official Python documentation](https://docs.python.org/3.7/library/urllib.request.html#legacy-interface)

@kjallen and I think there should be options to set network timeout(s) and number of retries for retrieving a resource. I think that `wget` is a good potential model for a CLI (`--tries`, `--waitretry`, `--timeout`, `--dns-timeout`, `--connect-timeout`, `--read-timeout` -- implementing all of these may or may not be overkill).

Making such a change also entails replacing `urlretrieve` (since it doesn't accept a `timeout` argument), probably with "Requests", as is suggested by the [docs](https://docs.python.org/3.4/library/urllib.request.html#urllib.request.urlretrieve). Requests supports all of ResourceSync's target Python versions.

**Comment by zimeon** [comment]
Fixed by #35

**Comment by zimeon** [comment]
This is now in 1.0.9 on [pypi](https://pypi.org/project/resync/)
