### ISSUE TITLE
Handling (resourcelist) indices dynamically

### ISSUE THREAD

**Issue by behas** [resync/resync#7]
I am wondering how to implement (resourcelist) indices dynamically using the resync library.
- The current ResourceListHandler in http.py should, depending on the number of resources, either return a sitemap or a site map index. I guess this covered by the as_xml() function.
- I can implement another handler ResourceListPartHandler that, in case ResourceListHandler returns an index, handles the "parts", i.e., the sitemaps. I could either introduce a separate path (/resourcelists/resourcelist0.xml) or just keep them in the same path and react to digit sequences in the "resourcelist….xml" pattern.

The question is now how the resync library could support of resource list parts. Could you provide a function 

as_xml(partnumber=x) where x is the digit sequence of the part URI, e.g. 0 in resourcelist0.xml

**Comment by zimeon** [comment]
This was resolved in v0.6. Haven't had issues with multi-file resource lists since then
